# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Var',
            new_name='Varia',
        ),
    ]
