# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171205_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='step1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step1', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step10', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step11', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step12', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step2', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step3', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step4', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step5', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step6', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step7', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step8', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='output',
            name='step9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step9', to='core.Step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='endVar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endVar', to='core.Var'),
        ),
        migrations.AlterField(
            model_name='step',
            name='startVar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startVar', to='core.Var'),
        ),
        migrations.AlterField(
            model_name='var',
            name='row1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row1', to='core.Row'),
        ),
        migrations.AlterField(
            model_name='var',
            name='row2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row2', to='core.Row'),
        ),
        migrations.AlterField(
            model_name='var',
            name='row3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row3', to='core.Row'),
        ),
        migrations.AlterField(
            model_name='var',
            name='row4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row4', to='core.Row'),
        ),
        migrations.AlterField(
            model_name='var',
            name='row5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row5', to='core.Row'),
        ),
    ]
