# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171205_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='number_of_steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_str',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='var',
            name='col_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='var',
            name='row_length',
            field=models.IntegerField(null=True),
        ),
    ]
