# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171205_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_str',
            field=models.TextField(null=True),
        ),
    ]
