# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171206_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='endVar',
        ),
        migrations.RemoveField(
            model_name='step',
            name='startVar',
        ),
        migrations.RemoveField(
            model_name='output',
            name='number_of_steps',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step1',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step10',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step11',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step12',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step3',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step4',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step5',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step6',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step7',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step8',
        ),
        migrations.RemoveField(
            model_name='output',
            name='step9',
        ),
        migrations.AddField(
            model_name='output',
            name='endVar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endVar', to='core.Var'),
        ),
        migrations.AddField(
            model_name='output',
            name='startVar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startVar', to='core.Var'),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
