# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171206_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='col_size',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='input',
            name='row_size',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
    ]
