# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171206_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_type',
            field=models.CharField(choices=[('add', 'ADD'), ('multiply', 'MULTIPLY'), ('rref', 'RREF'), ('determinant', 'DETERMINANT'), ('inverse', 'INVERSE')], max_length=12),
        ),
    ]
