# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20171206_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='var',
            name='profile',
            field=models.ForeignKey(default='guest', on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
            preserve_default=False,
        ),
    ]
