# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171207_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='var',
            name='profile',
        ),
    ]
